name: 'Deployment Auto Approve'
description: 'Automatic approval of Deployment reviews'
branding:
  icon: 'check'
  color: 'green'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  environment:
    description: 'Environment to pre-approve deployment'
    required: true
runs:
  using: 'node20'
  main: 'app/index.js'